name: Ping Render Sites

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 10 minutes
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Rant With Rose
        run: curl -s https://rant-with-rose.onrender.com/ > /dev/null
